config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  resources :users
  resources :cart_items
  resources :products
  resources :ratings
  resources :suggest_products
  resources :carts
  resources :comments
  resources :orders
  namespace :admin do
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :suggest_products
    resources :csv, only: :create
    resources :charts, :line_chart
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy

  belongs_to :user

  validates :receiver_name, presence: true, length: {maximum: Settings.maximum.name}
  validates :receiver_address, presence: true, length: {maximum: Settings.maximum.address}
  validates :receiver_phone, presence: true, length: {maximum: Settings.maximum.phone}
  validates :user_id, presence: true

  scope :by_search, ->start_day, end_day do
    where "Date(created_at) >= '#{start_day}' AND Date(created_at) <= '#{end_day}'" if start_day.present? and end_day.present?
  end

  def total_price
    order_items.includes(:product).to_a.sum {|item| item.total_price}
  end

  def group_by_order
    created_at.to_date.to_s(:db)
  end

  def total_quantity
    order_items.to_a.sum {|item| item.quantity}
  end

  scope :by_name, ->name do
    where "receiver_name LIKE '%#{name}%'" if name.present?
  end

  scope :by_status, ->status do
    where "status = #{status}" if status.present?
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :verify_admin

  def index
    @orders = Order.by_name(params[:search]).by_status params[:status]
  end

  def edit
    @order = Order.new
  end

  def update
    @order = Order.find_by id: params[:id]
    @order.status = params[:status]
    @user = User.find @order.user_id
    if @order.save
      case @order.status
      when 0
        flash[:success] = "You had choosed Pending"
      when 1
        flash[:success] = "You had choosed Approve"
        UserMailer.orders_success(@user,"aprove").deliver_now
      when 2
        flash[:success] = "You had choosed Reject"
        UserMailer.orders_success(@user,"Reject").deliver_now
      end
      redirect_to request.referer
    else
      render :edit
    end
  end
end

app/controllers/orders_controller.rb
  class OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :load_order, except: [:index, :create]

  def index
    @orders = current_user.orders.paginate page: params[:page],
      per_page: Settings.per_page.order
  end

  def show
  end

  def create
    @order = current_user.orders.build order_params
    ActiveRecord::Base.transaction do
      if @order.save
        current_user.send_order_email
        add_order_item
        destroy_cart
      else
        flash_slq_error @order
      end
    end
  end

  def edit
    respond
  end

  def update
    if @order.update_attributes order_params
      respond
    else
      flash_slq_error @order
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      @order.order_items.each do |item|
        update_product item
      end
      if @order.destroy
        respond
      else
        flash_slq_error @order
      end
    end
  end

  private
  def load_order
    @order = Order.find_by id: params[:id]
    unless @order
      flash[:danger] = t "error.order_not_found"
      redirect_to root_url
    end
  end

  def destroy_cart
    if Cart.destroy current_cart
      cookies.permanent.signed[:cart_id] = nil
      flash[:success] = t "order_success"
    else
      flash[:success] = t "destroy_cart_fail"
    end
    redirect_to root_path
  end

  def update_product item
    product = Product.find_by id: item.product_id
    unless product
      flash[:danger] = t "error.product_not_found"
      redirect_to root_url
    end
    product.quantity += item.quantity
    unless product.save
      flash_slq_error product
    end
  end

  def respond
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  def add_order_item
    current_cart.cart_items.each do |item|
      order_item = @order.order_items.build(
        product_id: item.product_id, quantity: item.quantity,
        order_price: item.cart_price)
      unless order_item.save
        flash_slq_error order_item
      end
      product = item.product
      product.number_of_order += item.quantity
      unless product.save
        flash_slq_error product
      end
    end
  end

  def order_params
    params.require(:order).
      permit :receiver_name, :receiver_phone, :receiver_address, :validate
  end

  def flash_slq_error object
    flash[:danger] = object.errors.full_messages
    redirect_to root_url
  end
end

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h2><%= t ".list_orders" %></h2>
    <%= form_tag admin_orders_path, method: "get" do %>
      <div class="input-group" id="adv-search">
        <%= text_field_tag :search, params[:search], placeholder: "search products",
          class: "form-control  a" %>
        <div class="input-group-btn">
          <div class="btn-group" role="group">
            <div class="dropdown dropdown-lg">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                aria-expanded="false"><span class="caret"></span></button>
              <div class="dropdown-menu dropdown-menu-right" role="menu">
                <form class="form-horizontal" role="form">
                  <div class="form-group">
                    <label for="filter">Status</label>
                    <%= select_tag :status, options_for_select([["Pending",0], ["Approve", 1], ["Reject", 2]], params[:status]), class: "form-control" %>
                   </div>
                </form>
              </div>
            </div>
            <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <h2 class="col-md-5 col-md-offset-3"><%= t ".list_orders" %></h2>
  <table class="table table-hover">
    <thead>
      <tr class="info row">
        <th class="col-md-1"><%= t ".quantity" %></th>
        <th class="col-md-1"><%= t ".total_price" %></th>
        <th class="col-md-2"><%= t ".name" %></th>
        <th class="col-md-2"><%= t ".address" %></th>
        <th class="col-md-2"><%= t ".phone" %></th>
        <th class="col-md-1"><%= t ".status" %></th>
        <th class="col-md-3"><%= t ".options" %></th>
      </tr>
    </thead>
    <tbody>
      <% if @orders.any? %>
        <% @orders.each do |order|%>
          <tr class="row">
            <td class="col-md-1"><%= order.total_quantity %></td>
            <td class="col-md-1"><%= order.total_price %></td>
            <td class="col-md-2"><%= order.receiver_name %></td>
            <td class="col-md-2"><%= order.receiver_address %></td>
            <td class="col-md-2"><%= order.receiver_phone %></td>
            <td class="col-md-1">
              <% if order.status == 0 %>
                <span class="btn-warning"> <%= t("pending")%> </span>
              <% elsif order.status == 1 %>
                <span class="btn-info"> <%= t("approve")%> </span>
              <% else %>
                <span class="btn-danger"> <%= t("reject")%> </span>
              <% end %>
            </td>
            <td class="col-md-3">
              <%= link_to t("pending"), admin_order_path(order, status: 0),
                method: :put, remote: true, class: "btn btn-warning margin_width" %>
              <%= link_to t("approve"), admin_order_path(order, status:1),
                method: :put, remote: true, class: "btn btn-info margin_width " %>
              <%= link_to t("reject"), admin_order_path(order, status:2),
                method: :put, remote: true, class: "btn btn-danger margin_width " %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>