config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  resources :users
  resources :cart_items
  resources :products
  resources :ratings
  resources :suggest_products
  resources :carts
  resources :comments
  resources :orders
  namespace :admin do
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :suggest_products
    resources :csv, only: :create
    resources :charts, :line_chart
  end
end

app/controllers/admin/charts_controller.rb
class Admin::ChartsController < ApplicationController
  def index
    @order = Order.by_search params[:start_day], params[:end_day]
    @order_array = @order.group_by(&:group_by_order).map {|k,v| [k, v.length]}.sort
    @user = User.by_search_user params[:start_day], params[:end_day]
    @user_array = @user.group_by(&:group_by_user).map {|k,v| [k, v.length]}.sort
  end
end

app/views/admin/charts/index.html.erb
<div class="container-fluid">
  <div class="margin_top"><%= t ".today" %> : <%= Time.now.strftime(Settings.date_format) %></div>
  <%= form_tag admin_charts_path, class: "form-horizontal bucket-form margin_top", method: "get" do %>
    <p>
      <%= text_field_tag :start_day, params[:start_day], class: "date", placeholder: "start day", id: "from"  %>
      <%= text_field_tag :end_day, params[:end_day], placeholder: "end day", id: "to" %>
      <%= submit_tag "Search", start_day: nil, end_day: nil, class: "btn-info btn"%>
    </p>
  <% end %>
  <div class=" col-md-8 col-md-offset-5"> <h6>Data Orders </h6> </div>
  <div class="margin_top"> <%= column_chart @order_array %> </div>
  <div class=" col-md-8 col-md-offset-5"> <h6>Data User </h6> </div>
  <div class="margin_top"> <%= column_chart @user_array %> </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
     $("#to").datepicker({ dateFormat: 'yyyy-mmm-dd' });
     $("#from").datepicker({ dateFormat: 'yyyy-mmm-dd' }).bind("change",function(){
            var minValue = $(this).val();
            minValue = $.datepicker.parseDate("yyyy-mmm-dd", minValue);
            minValue.setDate(minValue.getDate()+1);
            $("#to").datepicker( "option", "minDate", minValue );
        })
  });


  // $(function() {
  //   $('#datetimepicker').datetimepicker({
  //     pickTime: false
  //   });
  // });
</script>