config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  resources :users
  resources :cart_items
  resources :products
  resources :ratings
  resources :suggest_products
  resources :carts
  resources :comments
  resources :orders
  namespace :admin do
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :suggest_products
    resources :csv, only: :create
    resources :charts, :line_chart
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :recently_vieweds, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :comments, dependent: :destroy

  belongs_to :category

  validates :name,  presence: true, length: {maximum: Settings.maximum.name}
  validates :price, presence: true, numericality: true
  validates :quantity, presence: true, numericality: {only_integer: true}
  validates :category_id, presence: true

  scope :of_ids, -> ids {where id: ids}
  scope :top_order_products, -> {order "number_of_order desc"}
  scope :top_new_products, -> {order "created_at desc"}

  scope :by_category, ->category_id do
    where category_id: category_id if category_id.present?
  end

  scope :by_name, ->name do
    where "name LIKE '%#{name}%'" if name.present?
  end

  scope :by_min_price, ->min do
    where "price >= #{min}" if min.present?
  end

  scope :by_max_price, ->max do
    where "price <= #{max}" if max.present?
  end
  
  def list_users_rated_product
    User.of_ids Rating.user_ids_by_product self.id
  end

  def rated_by? user
    self.list_users_rated_product.include? user
  end

  def average_rate
    ((ratings.to_a.sum {|item| item.score}).to_f/ratings.count).
      round(Settings.default.round)
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.slice(*row.to_hash.keys)
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :verify_admin
  before_action :load_all_leaf_categories

  def new
    @product = Product.new
  end

  def index
    @products = Product.order(created_at: :DESC).paginate per_page:
      Settings.per_page.users, page: params[:page]
  end

  def show
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:danger] = t("flash.danger.invalid_user")
      redirect_to root_url
    end
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".create_product_success"
    else
      flash[:danger] = t ".create_product_fail"
    end
    redirect_to request.referer
  end

  def edit
    @product = Product.find_by id: params[:id]
  end

  def update
    @product = Product.find_by id: params[:id]
    if @product.update_attributes(product_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to :back
    else
      redirect_to request.referer
    end
  end

  def destroy
    product = Product.find_by id: params[:id]
    if product.destroy
      flash[:success] = t ".product_delete"
    else
      flash[:danger] = t ".product_not_found"
    end
    redirect_to request.referer
  end

  private
  def product_params
    params.require(:product).permit :name, :description, :image, :quantity,
     :price, :category_id
  end

  def load_all_leaf_categories
    @categories_leaf = Category.all.reject {|category| }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show
  before_action :new_user
  
  def index 
    @products = Product.by_name(params[:name])
      .by_category(params[:category]).by_min_price(params[:min])
      .by_max_price params[:max] 
    if params[:rate].present?
      @products = @products.select do |product| 
        product.average_rate > params[:rate].to_i
      end
    end
  end

  def show
    @cart_item = CartItem.new
    @comments = @product.comments
    if is_logged_in?
      save_recently_view
      if @product.rated_by? current_user
        @rating = current_user.ratings.find_by product_id: @product.id
        unless @rating
          redirect_to @product
          flash[:danger] = "error.rating_not_found"
        end
      else
        @rating = Rating.new
      end
    end
  end

  private
  def load_product
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:danger] = t "error.product_not_found"
      redirect_to root_url
    end
  end

  def save_recently_view
    recently_view = current_user.recently_vieweds.find_by_product_id @product.id
    unless recently_view
      recently_view = current_user.recently_vieweds.build product_id: @product.id
      if recently_view.save   
        if current_user.recently_vieweds.count > Settings.default.recently
          RecentlyViewed.destroy current_user.recently_vieweds.first
        end
      else
        flash[:danger] = recently_view.errors.full_messages
        redirect_to root_url
      end
    end
  end
end

app/views/admin/products/_product.html.erb
<tr>
  <td class="col-sm-4  order-info" id="receiver-info">
    <%= link_to product.name, [:admin, product] %>
  </td>
  <td class="col-sm-2 text-center">
    <%= image_tag product.image %>
  </td>
  <td class="col-sm-2 text-center item-total-price ">
    <div id= "cart-item-total-description">
      <%= product.description %>
    </div>
  </td>
  <td class="col-sm-2 text-center">
    <%= product.price %>
  </td>
  <td class="col-sm-2 text-center">
    <%= link_to "", [:admin, product], class: "glyphicon glyphicon-trash btn btn-danger ",
      method: :delete, data: {confirm:t("you_sure")} %>
  </td>
  <td class="col-sm-4  order-info" id="receiver-info">
    <%= link_to "", edit_admin_product_path(product), class: "glyphicon glyphicon-pencil btn btn-info",
      title: t("edit") %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<h1 class="col-md-8 col-md-offset-3"><%= t("update_product") %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for [:admin, @product], html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control", required: true %>
      </div>
      <div class="form-group ">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control col-md-2"  %>
      </div>
      <div class="form-group">
        <%= f.label :quantity %>
        <%= f.number_field :quantity, class: "form-control", required: true %>
      </div>
      <div class="form-group" >
        <%= f.label :price %>
        <%= f.text_field :price, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :category_id %>
        <%= f.select :category_id, options_for_select( @categories_leaf.collect{|cat|[cat.name, cat.id]}, class: "form-control" ) %>
      </div>
      <%= f.submit t("create_product"), class: "btn btn-primary btn-block" %>
    <% end %>
  </div>

app/views/admin/products/index.html.erb
<% provide :title, t("all_product") %>
<h1><%= t("all_product") %> </h1>
<div class="row">
<div class="col-md-8">
<table class="table table-hover">
  <thead>
    <tr class="info">
      <th class="text-center"><%= t("product_name") %></th>
      <th class="text-center"><%= t("image") %></th>
      <th class="text-center"><%= t("description") %></th>
      <th class="text-center"><%= t("price") %></th>
      <th class="text-center"></th>
      <th class="text-center"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @products %>
    <%= will_paginate  %>
  </tbody>
</table>
</div>
<div class="col-md-4">
  <div class="modal-body">
     <strong> <%= t("import_file")%> </strong>
     <%= form_tag admin_csv_index_path, multipart: true do %>
     <%= file_field_tag :file %>
     <%= submit_tag "submit", class: "btn btn-primary" %>
     <% end %>
  </div>
 </div>

</div>

app/views/admin/products/new.html.erb
<% provide :title, t("create_product") %>
<h1 class="col-md-8 col-md-offset-3"><%= t("create_product") %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for [:admin, @product], method: :post, html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control", required: true %>
      </div>
      <div class="form-group ">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control col-md-2"  %>
      </div>
      <div class="form-group">
        <%= f.label :quantity %>
        <%= f.number_field :quantity, class: "form-control", required: true %>
      </div>
      <div class="form-group" >
        <%= f.label :price %>
        <%= f.text_field :price, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :category_id %>
        <%= f.select :category_id, options_for_select( @categories_leaf.collect{|cat|[cat.name, cat.id]}, class: "form-control" ) %>
      </div>
      <%= f.submit t("create_product"), class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<% provide :title, @product.name %>
<div class="row">
<div class="col-md-8">
<table class="table table-hover">
  <thead>
    <tr>
      <th class="text-center"><%= t("product_name") %></th>
      <th class="text-center"><%= t("image") %></th>
      <th class="text-center"><%= t("description") %></th>
      <th class="text-center"><%= t("price") %></th>
      <th class="text-center"></th>
    </tr>
 </thead>
 <tbody>
    <tr>
  <td class="col-sm-4  order-info" id="receiver-info">
    <%= @product.name %>
  </td>
  <td class="col-sm-2 text-center">
    <%= image_tag @product.image %>
  </td>
  <td class="col-sm-2 text-center item-total-price ">
    <div id= "cart-item-total-description">
      <%= @product.description %>
    </div>
  </td>
  <td class="col-sm-2 text-center">
    <%= @product.price %>
  </td>
</tr>
</tbody>